<template>
  <div class="whatsapp-integration">
    <Card class="glass-card">
      <template #header>
        <div class="flex items-center gap-3 p-4 pb-0">
          <div class="w-10 h-10 rounded-full bg-green-500 flex items-center justify-center">
            <i class="pi pi-whatsapp text-white text-xl"></i>
          </div>
          <div>
            <h3 class="text-white font-bold text-lg mb-1">Share via WhatsApp</h3>
            <p class="text-white/70 text-sm">Send your plan directly to WhatsApp</p>
          </div>
        </div>
      </template>

      <template #content>
        <div class="space-y-6">
          <!-- Phone Number Input -->
          <div class="space-y-2">
            <label for="phone" class="block text-white font-medium text-sm">
              Phone Number
            </label>
            <div class="relative">
              <IconField>
                <InputText
                  id="phone"
                  v-model="phoneNumberModel"
                  placeholder="Enter phone number (e.g., +1234567890)"
                  class="w-full"
                  :class="{ 'border-red-500': phoneError }"
                />
              </IconField>
              <div v-if="phoneError" class="absolute -bottom-5 left-0">
                <small class="text-red-400">{{ phoneError }}</small>
              </div>
            </div>
          </div>

          <!-- Plan Preview -->
          <div v-if="planContent" class="space-y-2">
            <label class="block text-white font-medium text-sm">
              Plan Preview
            </label>
            <div class="glass-card p-4 max-h-32 overflow-y-auto">
              <p class="text-white/80 text-sm whitespace-pre-wrap">{{ truncatedPlan }}</p>
              <p v-if="planContent.length > 200" class="text-white/60 text-xs mt-2">
                ...and {{ planContent.length - 200 }} more characters
              </p>
            </div>
          </div>

          <!-- Action Buttons -->
          <div class="flex gap-3">
            <Button
              @click="shareToWhatsApp"
              :disabled="!canShare"
              :loading="isSharing"
              class="flex-1"
              severity="success"
            >
              <i class="pi pi-whatsapp mr-2"></i>
              Share to WhatsApp
            </Button>
            
            <Button
              @click="copyWhatsAppLink"
              :disabled="!canShare"
              outlined
              severity="success"
              v-tooltip="'Copy WhatsApp link'"
            >
              <i class="pi pi-copy"></i>
            </Button>
          </div>

          <!-- Help Text -->
          <div class="text-center">
            <small class="text-white/60">
              Make sure WhatsApp is installed on your device for direct sharing
            </small>
          </div>
        </div>
      </template>
    </Card>

    <!-- Success Toast -->
    <Toast />
  </div>
</template>

<script setup>
import { ref, computed, watch } from 'vue'
import { usePlanStore } from '../stores/planStore.js'
import { useToast } from 'primevue/usetoast'
import Card from 'primevue/card'
import Button from 'primevue/button'
import InputText from 'primevue/inputtext'
import IconField from 'primevue/iconfield'
import Toast from 'primevue/toast'
import '../main.css'

// Props
const props = defineProps({
  planContent: {
    type: String,
    default: ''
  }
})

// Composables
const planStore = usePlanStore()
const toast = useToast()

// Local state
const isSharing = ref(false)
const phoneError = ref('')

// Computed properties
const phoneNumberModel = computed({
  get: () => planStore.phoneNumber,
  set: (value) => {
    planStore.setPhoneNumber(value)
    validatePhoneNumber()
  }
})

const canShare = computed(() => {
  return planStore.isValidPhoneNumber && (props.planContent || planStore.generatedPlan)
})

const truncatedPlan = computed(() => {
  const content = props.planContent || planStore.generatedPlan
  return content.length > 200 ? content.substring(0, 200) + '...' : content
})

const whatsappMessage = computed(() => {
  const content = props.planContent || planStore.generatedPlan
  const header = "🌟 My Dream Weaver AI Plan 🌟\n\n"
  const footer = "\n\n✨ Generated by Dream Weaver AI ✨"
  return encodeURIComponent(header + content + footer)
})

const whatsappUrl = computed(() => {
  if (!canShare.value) return ''
  const cleanPhone = planStore.phoneNumber.replace(/[^\d+]/g, '')
  return `https://wa.me/${cleanPhone}?text=${whatsappMessage.value}`
})

// Methods
const validatePhoneNumber = () => {
  phoneError.value = ''
  
  if (!planStore.phoneNumber) {
    phoneError.value = 'Phone number is required'
    return
  }
  
  if (!planStore.isValidPhoneNumber) {
    phoneError.value = 'Please enter a valid phone number'
    return
  }
}

const shareToWhatsApp = async () => {
  if (!canShare.value) {
    toast.add({
      severity: 'warn',
      summary: 'Cannot Share',
      detail: 'Please enter a valid phone number and ensure you have a plan to share',
      life: 3000
    })
    return
  }

  isSharing.value = true

  try {
    // Check if we're on mobile and can use native sharing
    if (navigator.share && /Android|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) {
      await navigator.share({
        title: 'My Dream Weaver AI Plan',
        text: props.planContent || planStore.generatedPlan,
        url: whatsappUrl.value
      })
    } else {
      // Fallback to opening WhatsApp Web
      window.open(whatsappUrl.value, '_blank')
    }

    toast.add({
      severity: 'success',
      summary: 'Shared Successfully',
      detail: 'Your plan has been shared to WhatsApp',
      life: 3000
    })
  } catch (error) {
    if (error.name !== 'AbortError') {
      console.error('Error sharing to WhatsApp:', error)
      toast.add({
        severity: 'error',
        summary: 'Share Failed',
        detail: 'Failed to share to WhatsApp. Please try again.',
        life: 3000
      })
    }
  } finally {
    isSharing.value = false
  }
}

const copyWhatsAppLink = async () => {
  if (!canShare.value) return

  try {
    await navigator.clipboard.writeText(whatsappUrl.value)
    toast.add({
      severity: 'success',
      summary: 'Link Copied',
      detail: 'WhatsApp link copied to clipboard',
      life: 3000
    })
  } catch (error) {
    console.error('Error copying to clipboard:', error)
    toast.add({
      severity: 'error',
      summary: 'Copy Failed',
      detail: 'Failed to copy link. Please try again.',
      life: 3000
    })
  }
}

// Watch for phone number changes to clear errors
watch(() => planStore.phoneNumber, () => {
  if (phoneError.value && planStore.phoneNumber) {
    setTimeout(validatePhoneNumber, 300)
  }
})
</script>

<style scoped>
.whatsapp-integration {
  max-width: 500px;
  margin: 0 auto;
}

.glass-card {
  backdrop-filter: blur(16px);
  -webkit-backdrop-filter: blur(16px);
}

.p-button.p-button-success {
  background: linear-gradient(135deg, #25d366 0%, #128c7e 100%);
  border: none;
}

.p-button.p-button-success:hover {
  background: linear-gradient(135deg, #128c7e 0%, #25d366 100%);
  transform: translateY(-2px);
}

.p-button.p-button-outlined.p-button-success {
  background: rgba(37, 211, 102, 0.1);
  border: 1px solid rgba(37, 211, 102, 0.3);
  color: #25d366;
}

.p-button.p-button-outlined.p-button-success:hover {
  background: rgba(37, 211, 102, 0.2);
  border-color: #25d366;
}

.p-inputtext.border-red-500 {
  border-color: #ef4444 !important;
  box-shadow: 0 0 0 2px rgba(239, 68, 68, 0.2) !important;
}
</style>